Light, Shape, Messages, Material Params - interacting with scene mess…
toyota-connected/plugins pull request #3
Opened 2024-07-24 18:43 UTC by tcadanklefsen

…ages.

- Refactor out copying/saving references to custommodelviewer everywhere, turned into singleton (for now). Important info to be extracted out to new singleton. 
- Shape manager v1 boilerplate in with a 2 sided cube. Tasking to add more shapes backlogged. 
- Model loader now loads multiple models.
- Material params are now set (color and float only added properties for now), with warning if you try to set materials not declared  yet. 
- Added ability to dynamically change lighting easier. 
- Added messages for more gameplay related / demo-ness.

2024-07-26 20:45 UTC, jwinarske requested changes
* Trace is only used for critical bring up items
* All uppercase are only present in Debug builds, and get optimized out in Release builds.
* So either spdlog::debug (to include in Release), or SPDLOG_DEBUG
* Demo features need to be under a #define flag, defaulting to off.  Either define option in local CMake, or as #define in top level to library

2024-07-26 20:45 UTC, jwinarske commented on plugins/filament_view/core/include/file_utils.h
> +  SPDLOG_TRACE("Reading: {}/{}", main_path, dependent_path);
This should remain debug.  Trace enabled includes the backend context switching.  It get's very busy.

2024-07-26 20:45 UTC, jwinarske commented on plugins/filament_view/core/include/file_utils.h
> +  SPDLOG_TRACE("Read: {} bytes", size);
same as above.

2024-07-26 20:45 UTC, jwinarske commented on plugins/filament_view/viewer/custom_model_viewer.h
> +  void doDemoGameplayLoop(const float fDeltaTime);
what is this for?

2024-07-26 20:45 UTC, jwinarske commented on plugins/filament_view/viewer/custom_model_viewer.cc
> +      doDemoGameplayLoop((float)deltaTime / 1000);
Please add anything related to a demo under a #define, with it disabled by default.

2024-08-17 05:12 UTC, jwinarske requested changes
I checked in the clang-format and clang-tidy when I mentioned it prior.  You'll need to update that and rebase.

* Comment using `#if 0 //TODO - <comment>` pattern.  It needs to indicate why it's there.  If not a good reason delete the code.
* A singleton for the model viewer breaks multiple filament views at the same time
* The nav render plugin should not be part of this PR

2024-08-17 05:12 UTC, jwinarske commented on plugins/filament_view/CMakeLists.txt
> +# pkg_check_modules(SDL2 IMPORTED_TARGET sdl2)
Why is this commented out?

2024-08-17 05:12 UTC, jwinarske commented on plugins/filament_view/core/model/loader/model_loader.cc
> +    // TODO THROW ERROR
Agreed.  It needs an error class

2024-08-17 05:12 UTC, jwinarske commented on plugins/filament_view/core/model/loader/model_loader.h
> +  //   void fetchResources(
best to use 
```
#if 0 //TODO
...
#endif  //TODO
```

2024-08-17 05:12 UTC, jwinarske commented on plugins/filament_view/core/scene/camera/camera.cc
> +      }  // else if (std::holds_alternative<std::monostate>(it.second)) {
use #if 0 pattern as mentioned above

2024-08-17 05:12 UTC, jwinarske commented on plugins/filament_view/core/scene/camera/camera.h
> +  static constexpr char kModeAutoOrbit[] = "AUTOORBIT";
Can you document AUTOORBIT somewhere?

2024-08-17 05:12 UTC, jwinarske commented on plugins/filament_view/core/scene/camera/camera_manager.cc
> +  CustomModelViewer* modelViewer = CustomModelViewer::Instance(__FUNCTION__);
How would this work with multiple filament views?

2024-08-17 05:12 UTC, jwinarske commented on plugins/filament_view/core/scene/material/loader/material_loader.cc
> +  SPDLOG_DEBUG("Material Informaton {}", material->getName());
These should be spdlog::info.  Say you want to print material info in release.  Calling this would produce no output.

2024-08-17 05:12 UTC, jwinarske commented on plugins/filament_view/core/scene/material/loader/texture_loader.cc
> +  static const int NUM_CHANNELS_FOR_IMAGE = 3;
constexpr, and use `kNumChannelsForImage` naming pattern.

2024-08-17 05:12 UTC, jwinarske commented on plugins/filament_view/core/scene/material/loader/texture_loader.cc
> -    std::string url,
We can't remove network loading of assets.  Consider a development workflow.

2024-08-17 05:12 UTC, jwinarske commented on plugins/filament_view/core/scene/scene_controller.cc
> +  // auto f = groundManager_->createGround();
Use `#if 0 //TODO - comment` so we know why it's commented and not deleted

2024-08-17 05:12 UTC, jwinarske commented on plugins/filament_view/core/shapes/shape.cc
> +#if 1
this should be removed

2024-08-17 05:12 UTC, jwinarske commented on plugins/filament_view/core/shapes/shape.cc
> +  // float unitVertices[] = {
use #if 0 //TODO - comment pattern, or delete

2024-08-17 05:12 UTC, jwinarske commented on plugins/filament_view/core/shapes/shape.cc
> +void Shape::createCube(::filament::Engine* engine_,
#if 0 //TODO - comment pattern or delete

2024-08-17 05:12 UTC, jwinarske commented on plugins/filament_view/messages.g.cc
> +            // TODO Make a literals for these values:
These should be added now using this pattern:
```
`static constexpr char kChangeLightColorByIndex[] = "CHANGE_LIGHT_COLOR_BY_INDEX"`
```

2024-08-17 05:12 UTC, jwinarske commented on plugins/filament_view/messages.g.cc
> +            // const String _toggleShapesInScene = "TOGGLE_SHAPES_IN_SCENE";
same as above

2024-08-17 05:12 UTC, jwinarske commented on plugins/filament_view/messages.g.cc
> +            // const String _toggleCameraAutoRotate =
same as above

2024-08-17 05:12 UTC, jwinarske commented on plugins/filament_view/messages.g.cc
>  #if 0
needs a //TODO - comment.  We need to know what's going on.  Should we delete it, or use it.  It adds technical debt

2024-08-17 05:12 UTC, jwinarske commented on plugins/filament_view/viewer/custom_model_viewer.h
> +  // CustomModelViewer(const CustomModelViewer&) = delete;
use #if 0 //TODO - comment, or delete

2024-08-17 05:12 UTC, jwinarske commented on plugins/nav_render_view/libnav_render.h
this file is in an adjacent module.  It should only be limited to the filament view plugin

2024-08-17 05:12 UTC, jwinarske commented on plugins/nav_render_view/nav_render_error.h
same as above

2024-08-17 05:12 UTC, jwinarske commented on plugins/nav_render_view/nav_render_surface.cc
same as above

2024-08-17 05:12 UTC, jwinarske commented on plugins/nav_render_view/nav_render_texture.cc
same as above

2024-08-17 05:12 UTC, jwinarske commented on plugins/nav_render_view/nav_render_texture.h
same as above

2024-08-17 05:12 UTC, jwinarske commented on clang-format
this file is already checked in

2024-08-17 05:12 UTC, jwinarske commented on clang-tidy
this file is already checked in

2024-08-19 15:29 UTC, tcadanklefsen commented on plugins/filament_view/CMakeLists.txt
> +# pkg_check_modules(SDL2 IMPORTED_TARGET sdl2)
This one fails to build by default.

2024-08-19 15:40 UTC, tcadanklefsen commented on plugins/filament_view/core/model/loader/model_loader.h
> +  //   void fetchResources(
Leftover from previous, removed.

2024-08-19 15:43 UTC, tcadanklefsen commented on plugins/filament_view/messages.g.cc
>  #if 0
This was prior code, no idea why its there - didnt write it. But i can definitely delete it if you want?

2024-08-19 16:59 UTC, tcadanklefsen commented on plugins/filament_view/messages.g.cc
> +            // const String _toggleCameraAutoRotate =
Fixed.

2024-08-19 16:59 UTC, tcadanklefsen commented on plugins/filament_view/messages.g.cc
> +            // const String _toggleShapesInScene = "TOGGLE_SHAPES_IN_SCENE";
Fixed.

2024-08-19 16:59 UTC, tcadanklefsen commented on plugins/filament_view/messages.g.cc
> +            // TODO Make a literals for these values:
Fixed. Thanks

2024-08-19 17:14 UTC, tcadanklefsen commented on plugins/filament_view/core/scene/material/loader/texture_loader.cc
> +  static const int NUM_CHANNELS_FOR_IMAGE = 3;
Fixed.

2024-08-19 17:17 UTC, tcadanklefsen commented on plugins/filament_view/core/shapes/shape.cc
> +#if 1
Added comment, next tasking to be implemented of moving init code out of here.

2024-08-19 17:18 UTC, tcadanklefsen commented on plugins/filament_view/core/shapes/shape.cc
> +  // float unitVertices[] = {
Active work for next iteration.

2024-08-19 17:19 UTC, tcadanklefsen commented on plugins/filament_view/core/shapes/shape.cc
> +void Shape::createCube(::filament::Engine* engine_,
Added comment, keeping to split in next'ish PR

2024-08-19 17:25 UTC, tcadanklefsen commented on plugins/filament_view/core/scene/camera/camera.h
> +  static constexpr char kModeAutoOrbit[] = "AUTOORBIT";
There's additional tasking backlogged for improvement here in another iteration; but yes, adding more info for now.

2024-08-19 17:30 UTC, tcadanklefsen commented on plugins/filament_view/core/scene/camera/camera.h
> +  static constexpr char kModeAutoOrbit[] = "AUTOORBIT";
Added comments, re-review

2024-08-19 17:32 UTC, tcadanklefsen commented on plugins/filament_view/core/scene/scene_controller.cc
> +  // auto f = groundManager_->createGround();
Removed / added comment.

2024-08-19 17:43 UTC, tcadanklefsen commented on plugins/filament_view/core/scene/material/loader/texture_loader.cc
> -    std::string url,
Adding this back in, this was failing to build on my fedora instance.

2024-08-26 22:05 UTC, jwinarske requested changes

2024-08-26 22:05 UTC, jwinarske commented on plugins/filament_view/CMakeLists.txt
> +# pkg_check_modules(SDL2 IMPORTED_TARGET sdl2)
fine for now.  will address in a later PR

2024-08-26 22:05 UTC, jwinarske commented on plugins/filament_view/core/scene/camera/camera_manager.cc
> +  CustomModelViewer* modelViewer = CustomModelViewer::Instance(__FUNCTION__);
Will be addressed in later PR

2024-08-26 22:05 UTC, jwinarske commented on plugins/filament_view/messages.g.cc
>  #if 0
it needs to be deleted.  Was a working example that should have been removed

2024-08-26 22:05 UTC, jwinarske commented on plugins/filament_view/viewer/custom_model_viewer.h
> +  // CustomModelViewer(const CustomModelViewer&) = delete;
Are you copying or assigning CustomModelViewer?

2024-08-27 13:58 UTC, tcadanklefsen commented on plugins/filament_view/viewer/custom_model_viewer.h
> +  // CustomModelViewer(const CustomModelViewer&) = delete;
I am not, added back in.

2024-08-27 13:59 UTC, tcadanklefsen commented on plugins/filament_view/messages.g.cc
>  #if 0
Deleted

2024-08-27 16:39 UTC, merged